# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mpfs-solutions"
BBFILE_PATTERN_meta-mpfs-solutions = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mpfs-solutions = "6"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_meta-mpfs-solutions = "1"

LAYERDEPENDS_meta-mpfs-solutions += "meta-mchp-common"
LAYERDEPENDS_meta-mpfs-solutions += "meta-mchp-polarfire-soc-bsp"
LAYERSERIES_COMPAT_meta-mpfs-solutions = "scarthgap styhead"
