# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-mchp-fpga-soln"
BBFILE_PATTERN_meta-mchp-fpga-soln = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-mchp-fpga-soln = "6"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_meta-mchp-fpga-soln = "1"

LAYERDEPENDS_meta-mchp-fpga-soln += "meta-mchp-common"
LAYERDEPENDS_meta-mchp-fpga-soln += "meta-mchp-polarfire-soc-bsp"
LAYERSERIES_COMPAT_meta-mchp-fpga-soln = "scarthgap styhead"
